"""
Create a text based game using Python that allows the player 
to travel left or right to move through a tree of locations. 
Branch endings should result in game overs or win.
"""
### ADD THE CODE GENERATED BY CHATGPT HERE ###


### Run your program and see if it works. Does it do what you expect?
### PUT YOUR ANSWER HERE ###

### How might you change this game to make it more fun? Come up with some ideas
### and then write some prompts to get ChatGPT to make your ideas into code.

### Here are some example prompts that you can play around with.
### Add some of yours here too. Also record what each prompt added to
### your program. 

'''What lines of code should I alter to change the story to one
that I wrote?'''
    
'''Change the game so that the player is also able to go back to
the previous location.'''

    # ADD YOUR PROMPTS HERE